### ISSUE TITLE
Cannot find package '@nuxt/kit-edge'

### ISSUE THREAD

**Issue by lucpotage** [windicss/nuxt-windicss#135]
New project with latest version of Nuxt 3 , Windi CSS module, and vite-svg-loader. I got the following error:

> Cannot start nuxt:  Cannot find package '@nuxt/kit-edge' imported from /node_modules/nuxt-windicss/dist/module.mjs
>   at new NodeError (node:internal/errors:371:5)
>   at packageResolve (node:internal/modules/esm/resolve:884:9)
>   at moduleResolve (node:internal/modules/esm/resolve:929:18)
>   at defaultResolve (node:internal/modules/esm/resolve:1044:11)
>   at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
>   at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
>   at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
>   at link (node:internal/modules/esm/module_job:75:36)

I wanted to make a CodeSandbox but I didn't know how to make it work with Nuxt 3.

**Comment by lucpotage** [comment]
This is strange because 2.0.4 was supposed to solve @nuxt/kit issue by using @nuxt/kit-edge. However, even after removing node_modules directory, yarn.lock file and running a fresh `yarn install` I get this error.

I currently have to explicitly add `@nuxt/kit-edge` as a dev dependency.

**Comment by harlan-zw** [comment]
Hey @lucpotage 

I've done an update that will use an explicit version of nuxt/kit-edge over `latest`, testing it locally it seems to be okay now. Maybe you can confirm for me

**Comment by silasabbott** [comment]
I'm still getting this same error using the latest `nuxt3@3.0.0-27258467.4e424d0` and `nuxt-windicss@2.0.10`.

**Comment by harlan-zw** [comment]
I've reverted to package.json to use the npm aliasing for 2.0.11,  it should fix this issue but may introduce the same problem again.

I have no way of replicating the issue, might be platform specific issue. Can you post the output of `yarn nuxi info` if you still have issues

**Comment by lucpotage** [comment]
It now works perfectly. Thank you!
