### ISSUE TITLE
loadNuxt not found

### ISSUE THREAD

**Issue by jbmolle** [windicss/nuxt-windicss#137]
**Describe the bug**
Bug with @nuxt/kit: latest
See https://github.com/nuxt/framework/issues/1795

**To Reproduce**
1. Install a basic nuxt3 app
2. Add nuxt-windicss 2.0.12

**Expected behavior**
The nuxt app should start but we get an error loadNuxt not found.

**Additional context**
The problem comes from @nuxt/kit: latest used in nuxt-windicss 2.0.12
Version 2.0.11 works correctly.
The problem with the @nuxt/kit proxy is that it allows CJS code (whereas @nuxt/kit-edge is ESM only)

A possible solution would be to revert to @nuxt/kit: "npm:@nuxt/kit-edge@latest" while the problem with @nuxt/kit: latest is solved. A warning says that CJS will be dropped when Nuxt3 is production ready which should be soon

**Comment by pi0** [comment]
The issue with the CJS default export should be gone if you recreate the lock file (Using `npx nuxi upgrade --force`)
