### ISSUE TITLE
Nuxt v3 `defineNuxtConfig` does not like  extending with `windicss:`

### ISSUE THREAD

**Issue by acidjazz** [windicss/nuxt-windicss#138]
ex:

```ts

export default defineNuxtConfig({
  ...
  srcDir: 'client/',
  /*
  ** https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#buildmodules
  */
  buildModules: [
    'nuxt-windicss',
    '@tailvue/nuxt',
  ],
  windicss: {
    darkMode: 'class', // or 'media' or 'class'
    extract: {
      include: [
        "./client/**/*.{vue,ts}",
        "node_modules/tailvue/dist/tailvue.es.js",
      ],
    },
  },
}
```

I get the following error

```
TS2345: Argument of type '{ srcDir: string; meta: { title: string; meta: ({ charset: string; } | { name: string; content: string; } | { hid: string; name: string; content: string; })[]; link: { rel: string; type: string; href: string; }[]; }; css: string[]; components: true; buildModules: string[]; windicss: { ...; }; }' is not assignable to parameter of type '{ components?: boolean | ComponentsOptions | (string | ComponentsDir)[] | { dirs?: (string | ComponentsDir)[] | (string | ComponentsDir | { ...; })[]; loader?: Boolean | { ...; }; } | (string | ... 1 more ... | { ...; })[]; ... 69 more ...; vite?: boolean | ... 1 more ... | { ...; }; }'.
```

Should/can the NuxtJS module extend and append to `defineNuxtConfig` ?

**Comment by ivanq3w** [comment]
You can use windi.config.ts instead:
![image](https://user-images.githubusercontent.com/58051684/143719108-1ecb9864-b1c0-48dc-bc70-b0ef7796e783.png)

**Comment by acidjazz** [comment]
@ivanq3w sure - i think there might be a more ideal fix though? maybe extending the nuxtconfig interface in this module?

**Comment by harlan-zw** [comment]
Hey @acidjazz 

Having the config typed is something that should definitely work. There have been quite a few changes in Nuxt 3 and bridge since I implemented support for it, breaking the initial config types.

I'll have a chat to them and see if I can figure out a solution

**Comment by acidjazz** [comment]
@harlan-zw I believe you can something like this to this module:


```ts
declare module '@nuxt/schema' {
  interface NuxtConfig {
    windicss?: WindiCSSConfig
  }
  interface NuxtOptions {
    windicss?: WindiCSSConfig
  }
}

```

**Comment by harlan-zw** [comment]
@acidjazz, @replygirl, @ivanq3w 

The issue should be fixed, thanks for reporting on it. Let me know if you have any difficulties.

You shouldn't need to add anything to the tsconfig.json, nuxt3 seems to take care of the type imports

**Comment by acidjazz** [comment]
@harlan-zw awesome stuff!!

**Comment by harlan-zw** [comment]
Oh and @acidjazz, your config probably needs to look like this

```
  windicss: {
        config: {
            darkMode: 'class', // or 'media' or 'class'
        },
        scan: {
            include: [
                "./client/**/*.{vue,ts}",
                "node_modules/tailvue/dist/tailvue.es.js",
            ],
        },
    },
```

**Comment by acidjazz** [comment]
testing this in v2.1.1 @harlan-zw and I get

```
Type '{ darkMode: string; extract: { include: string[]; }; }' is not assignable to type 'NuxtWindiOptions'.
  Object literal may only specify known properties, and 'darkMode' does not exist in type 'NuxtWindiOptions'.ts(2322)
index.d.ts(37, 9): The expected type comes from property 'windicss' which is declared here on type 'NuxtConfig'
```

![image](https://user-images.githubusercontent.com/967369/145333203-8389d2ff-5d41-4b4f-b7a9-e29c717f709e.png)

**Comment by harlan-zw** [comment]
(see above :P)

**Comment by acidjazz** [comment]
aha!! thanks @harlan-zw  - beat me to it

**Comment by acidjazz** [comment]
just curious @harlan-zw  - why a seperate config set and not just a mirror of windicss `defineConfig` ?

**Comment by acidjazz** [comment]
still getting errors BTW, and i don't see those definitions [here](https://github.com/windicss/nuxt-windicss/blob/main/packages/nuxt-windicss/src/types.ts#L11-L30)

**Comment by harlan-zw** [comment]
For anyone using PhpStorm / Webstorm, there seems to be a problem with Nuxt 3. I've created an issue here: https://github.com/nuxt/framework/issues/2320
