### ISSUE TITLE
Unclosed bracket bug

### ISSUE THREAD

**Issue by loremru** [windicss/nuxt-windicss#139]
![image](https://user-images.githubusercontent.com/66596500/142760884-975cf8be-5c69-4398-bb11-fb9b9d3a1a5d.png)

**Comment by harlan-zw** [comment]
Hey @loremru 

Sorry for the delay, seems like some of your CSS may be causing this, would you be able to share a reproduction issue?

**Comment by loremru** [comment]
@harlan-zw The error appears when I want to generate based on min.js with windi classes

**Comment by harlan-zw** [comment]
This may be fixed in the latest version, there was an issue with the pitcher which may of been causing problems
