### ISSUE TITLE
!Not working anymore with nuxt-bridge!

### ISSUE THREAD

**Issue by thomas4Bitcraft** [windicss/nuxt-windicss#149]
Our project was working since yesterday - if you reinstall the package now no styles all loaded anymore. As far as i see the only thing that changed is: 

![image](https://user-images.githubusercontent.com/44415527/147097819-533ff7ca-4469-445b-a100-90f212f2a8da.png)

**Comment by harlan-zw** [comment]
Hey @thomas4Bitcraft 

There was an update in @nuxt/kit which broke the package, it should be working now in version 2.2.1. Let me know if you have any further issues :)
