### ISSUE TITLE
Nuxt-Windicss no longer working with Nuxt3

### ISSUE THREAD

**Issue by TrungRueta** [windicss/nuxt-windicss#150]
**Describe the bug**
after nuxt 3 `3.0.0-27333388.c824905` nuxt-windicss no longer working anymore. Look like nuxt 3 change hook token and nuxt-windicss ignore. 

**To Reproduce**
1. Install nuxt 3
2. install nuxt-windicss
3. add windicss to buildModules 
4. run project
5. see in terminal, windi ignored

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TrungRueta** [comment]
@pi0 Dear, can you take time and take a look this issue. After your fix at https://github.com/nuxt/framework/discussions/2490 i see error about `Nuxt module should be a function` gone, but look like error just be ignore, some module like nuxt-windicss skiped when dev or build.
Thanks!

**Comment by ontoneio** [comment]
I am also having issues with Windi not working except in my case its for v`2.15.8` .
It was working fine then somewhere it just broke and wouldn't come back.

Here is my reproduction link.
[Code Sandbox](https://codesandbox.io/s/beautiful-goodall-wb5id?file=/components/Tutorial.vue)

**Comment by pi0** [comment]
Sorry for inconveniences. A PR is already there for upgrade https://github.com/windicss/nuxt-windicss/pull/148

**Comment by pi0** [comment]
Also added a quick fix for backward compatibility with current format https://github.com/nuxt/framework/commit/5a7a979dcb4dc74e92cce2c9c9bbddbb52a0d3d5

**Comment by harlan-zw** [comment]
Thanks for the issue @TrungRueta, and for the fix @pi0.

Testing 2.2.1 with Nuxt v3 seems to be working. Let me know if you have any other issues :)
