### ISSUE TITLE
Not working with Nuxt version `2.15.8`

### ISSUE THREAD

**Issue by ontoneio** [windicss/nuxt-windicss#151]
**Describe the bug**

Nuxt is no longer loading any Windi specific css.

**To Reproduce**
1. Fork this CodeSandbox [Nuxt Template](https://codesandbox.io/s/codesandbox-nuxt-zqxk0lw813)
2. Make sure nuxt is upgraded to latest version in dependencies dropdown
3. Add `nuxt-windicss` to dependencies
4. Remove inline `<link/>` tag that loads Tailwind in `Tutorial` component
5. Add `nuxt-windicss` to  `buildModules` in nuxt.config.js` 
6.  Restart Container/Server

**Expected behavior**
Since Tailwind and Windi share similar syntax you should expect to see styles being rendered correctly and see styles being loaded into the developer tools.

**Screenshots**

![image](https://user-images.githubusercontent.com/24515434/147152579-f852b9c2-d1d7-4bfa-8539-ecebc81a565d.png)
![image](https://user-images.githubusercontent.com/24515434/147153040-83e4431b-9d43-4f4d-b2f9-0e3de17640b5.png)

**Additional context**

Not sure where this issue came from, seemed to happen after I cleared my yarn cache and did some node_modules refreshing, but not positive, haven't been able to reproduce the actions that lead up to it not working.

**Comment by ontoneio** [comment]
Will close if this is covered by PR #148

**Comment by harlan-zw** [comment]
Hey @ontoneio 

Thanks for the detailed issue. Testing with the latest release, 2.2.1, it seems to be fixed :) Let me know if you have any more issues
