### ISSUE TITLE
2.2.1 causes fatal error

### ISSUE THREAD

**Issue by donaldrich80** [windicss/nuxt-windicss#153]
Just wanted to bring this to your attention.  The new release caused the following error... 

```
 FATAL  Named export 'isCI' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'std-env';
const { isDevelopment, isCI, isTest } = pkg;


  import { isDevelopment, isCI, isTest } from 'std-env';
  ^^^^
  SyntaxError: Named export 'isCI' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'std-env';
  const { isDevelopment, isCI, isTest } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
  at async Loader.import (node:internal/modules/esm/loader:178:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)

```

After removing it from nuxt.config.js, my project started again, and reverting to 2.2.0 got everything on track.

**Comment by harlan-zw** [comment]
@pi0 any ideas 🤔?

**Comment by donaldrich80** [comment]
I still have my windicss version pinned to the version prior to 2.2.1, and also decided to take the plunge and upgrade to nuxt-bridge over the holidays (so it will probably be comparing apples to oranges once I do decide upgrade windi-css).

I had isolated the only change correlated with the error to be the new version of windicss being installed & enabled.... that said, I believe ultimately that the node version being used could have probably been playing an unseen role in my issue (and it was not kept stable among machines/environments).

Regardless, windicss is AWESOME! Singlehandedly reduced my dev builds from like 10 min to a few seconds.

I'm closing this issue.

Happy 2022!

**Comment by harlan-zw** [comment]
> I still have my windicss version pinned to the version prior to 2.2.1, and also decided to take the plunge and upgrade to nuxt-bridge over the holidays (so it will probably be comparing apples to oranges once I do decide upgrade windi-css).
> 
> I had isolated the only change correlated with the error to be the new version of windicss being installed & enabled.... that said, I believe ultimately that the node version being used could have probably been playing an unseen role in my issue (and it was not kept stable among machines/environments).
> 
> Regardless, windicss is AWESOME! Singlehandedly reduced my dev builds from like 10 min to a few seconds.
> 
> I'm closing this issue.
> 
> Happy 2022!

Great to hear! Thanks 😄
