### ISSUE TITLE
Parts of the customization seems to be broken

### ISSUE THREAD

**Issue by DennisMaass** [windicss/nuxt-windicss#154]
**Describe the bug**
Parts of the customization seems to be broken

**To Reproduce**
extends theme: https://stackblitz.com/edit/nuxt-starter-92ekgi?file=pages%2Findex.vue
without extends: https://stackblitz.com/edit/nuxt-starter-nsmqsl?file=pages%2Findex.vue

**Expected behavior**
extends theme: The additional added classes should be available and working
without extends: my own theme should work

**Screenshots**
Extends
![Bildschirmfoto 2021-12-23 um 15 24 12](https://user-images.githubusercontent.com/11490121/147253452-cd0bb1c9-18b4-4b51-a788-d4335ce3e508.png)

without extends
![Bildschirmfoto 2021-12-23 um 15 24 08](https://user-images.githubusercontent.com/11490121/147253471-afcd9f20-2abd-4266-a8a3-ac3ea86d17e5.png)

**Additional context**
In addition sometimes you need 2 HRM cycles or a full restart to see the result

**Comment by harlan-zw** [comment]
Hey @DennisMaass 

Thanks for the reproduction repos. 

I believe there was a bug with the box-shadow customisation in 2.2.1, which seems to be sorted in 2.2.2 from your repo.

 Are you able to confirm

**Comment by DennisMaass** [comment]
Hey @harlan-zw,

Supplying a repository is the least I can do. 
I updated them and it works fine now!

Thanks you very much!
I wish you a happy new year.
