### ISSUE TITLE
Cannot find module 'postcss-loader/package.json'

### ISSUE THREAD

**Issue by huuhait** [windicss/nuxt-windicss#160]
![image](https://user-images.githubusercontent.com/40519768/152599728-5a062cfe-03e3-4cbe-ab0a-b96ef2453443.png)

**Comment by zernonia** [comment]
Hi @huuhait  , I'm facing this issue as well. What you did that fix this error ya?

**Comment by xby020** [comment]
> Hi @huuhait , I'm facing this issue as well. What you did that fix this error ya?

Same issue when I upgrade all packages to latest, and my solution is add `postcss-loader` to Dev dependencies.
```
yarn add postcss-loader --dev
```
But this solution is temporary cause I don't need this pack.
May have another better way.
