### ISSUE TITLE
Import createRouter does not exist in h3 export

### ISSUE THREAD

**Issue by daver987** [windicss/nuxt-windicss#170]
I get this error after I upgraded to the latest Nuxt 3 version

Nuxt CLI v3.0.0-27490192.4253d2e
Package Manager: yarn 1.22.18

**Describe the bug**
ERROR [worker reload] [worker init] The requested module 'PROJECT/node_modules/h3/dist/index.mjs' does not provide an export named 'createRouter'

import { handleCacheHeaders, toEventHandler, createApp, createRouter, lazyEventHandler, eventHandler, useQuery } from 'PROJECT/node_modules/h3/dist/index.mjs';
^^^^^^^^^^^^
SyntaxError: The requested module 'PROJECT/node_modules/h3/dist/index.mjs' does not provide an export named 'createRouter'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
at async loadESM (node:internal/process/esm_loader:88:5)
at async handleMainPromise (node:internal/modules/run_main:61:12)

Also before the update I was also having Issues where the styling wasn't working properly in dev mode, I would keep starting and stoping until the styles would apply properly, the styles would apply properly when I built the project

**Expected behavior**
That the module with load correctly.

This is related to the bug report on the Nuxt Framework 

https://github.com/nuxt/framework/issues/4205

**Comment by Louis-Tian** [comment]
Bumped into this as well. Most likely an upstream problem with Nuxt itself as @daver987 referenced.

**Comment by harlan-zw** [comment]
Thanks for reporting, this should be fixed in the newest version.

**Comment by daver987** [comment]
It started working again with the latest version of nuxt3, thanks for the great module!
