### ISSUE TITLE
Custom Colors not regsitered

### ISSUE THREAD

**Issue by king-11** [windicss/nuxt-windicss#176]
**Describe the bug**
Custom color classes are not working in nuxt windicss, or more aptly they are not getting generated as windicss-intellisense shows error for not being able to identify them.

**To Reproduce**

Open this [stackblitz container](https://stackblitz.com/edit/nuxt-starter-36i2nj?file=app.vue) and try adding custom color classes configured in windi.config.ts in app.vue

**Expected behavior**
Should be able to use custom color classes registered like `text-main-100`

**Screenshots**
![image](https://user-images.githubusercontent.com/52061363/170769628-9eb81fb8-7f26-4351-b72c-cfc2c3cd2754.png)

**Comment by harlan-zw** [comment]
Hey @king-11. Thanks for the reproduction

Not too sure where the expectation for that behaviour has come from. 

As far as I know, by setting colours as you have, it won't generate the 50-900 array of values. You will need to manually generate the array if you're providing custom colours or use the 1 colour you have provided (see https://stackblitz.com/edit/nuxt-starter-ttd9vh?file=app.vue).

**Comment by king-11** [comment]
@harlan-zw sorry for the trouble I had some confusion. Maybe we can add this in docs because I only realised it later after checking out the tailwindcss docs
