### ISSUE TITLE
Can not use sass variables when using Nuxt 3.

### ISSUE THREAD

**Issue by xiaoluoboding** [windicss/nuxt-windicss#177]
**Describe the bug**

Can not use sass variables when using Nuxt 3.

**To Reproduce**

Checkout: https://stackblitz.com/edit/nuxt-starter-27pv52

**Expected behavior**

Both use sass and windicss normally.

**Screenshots**

<img width="530" alt="CleanShot 2022-06-06 at 15 14 47@2x" src="https://user-images.githubusercontent.com/6118824/172113577-c09262c6-5cd3-4460-ad16-1ee544b2fae1.png">

**Additional context**

**Comment by crstnmac** [comment]
Facing similar issue

**Comment by ShaggyTech** [comment]
You'll have to use interpolation on the variable name.

 

> ...more recent versions of Sass require SassScript expressions in custom property values to be written within [interpolation](https://sass-lang.com/documentation/interpolation).

See [https://sass-lang.com/documentation/breaking-changes/css-vars](https://sass-lang.com/documentation/breaking-changes/css-vars)

```css
$--text-light: rgba(0, 0, 0, 0.75);

h1 {
  color: #{$--text-light};
}
```
