### ISSUE TITLE
broken build using latest nuxt (rc.10)

### ISSUE THREAD

**Issue by samydoesit** [windicss/nuxt-windicss#180]
**Describe the bug**
Nuxt-windicss breaks nuxt build using latest nuxt rc.10.

**To Reproduce**
1. open the stackblitz repro -> https://stackblitz.com/edit/github-jvn36e
2. See error

**Expected behavior**
Build should succeed without windicss errors.

**Screenshots**
<img width="812" alt="image" src="https://user-images.githubusercontent.com/15785987/189116671-9aa3b798-559a-4f95-b7df-b0fb0f25e029.png">

**Temporary workaround:**
add this to nuxt.config.ts
`  experimental: {
    inlineSSRStyles: false
  },`

**Comment by harlan-zw** [comment]
Thanks for flagging this. Might be a bit difficult to dig into this one so I'll wait for the official RC.10 release before digging into it.

The only commit that looks like it could be causing the issue is https://github.com/nuxt/framework/pull/7264

**Comment by danielroe** [comment]
See also https://github.com/unocss/unocss/issues/1536. For virtual css modules we need to respond to `?inline&used` as well; do drop me a DM if it would be helpful to work this through together.

**Comment by harlan-zw** [comment]
Fixed in 2.5.2, thanks to Daniel
