### ISSUE TITLE
nuxt 3.0.0-rc.13 使用nuxt-windicss生产环境报错

### ISSUE THREAD

**Issue by liuyang0623** [windicss/nuxt-windicss#195]
报错信息： [warn] Module `nuxt-windicss` is disabled due to incompatibility issues:
 - [nuxt] Nuxt version `^2.0.0 || ^3.0.0` is required but currently using `3.0.0-rc.13`
 - 
![image](https://user-images.githubusercontent.com/30205968/204957439-116b1e5e-d4da-4887-9115-17ffec79456c.png)
之前是好使的，昨天jenkins部署的时候突然不好使了

**Comment by harlan-zw** [comment]
Please use version 3.0.0 of Nuxt or use an earlier version of nuxt-windicss

**Comment by Upose** [comment]
so can't use nuxt3 latest?

**Comment by Upose** [comment]
> Please use version 3.0.0 of Nuxt or use an earlier version of nuxt-windicss

So how to make this to support the latest version of nuxt3

**Comment by harlan-zw** [comment]
This supports the latest version of Nuxt, which is 3.0.0?

Provide a `nuxi info` if you're having issues

**Comment by Upose** [comment]
> This supports the latest version of Nuxt, which is 3.0.0?
> 
> Provide a `nuxi info` if you're having issues

![image](https://user-images.githubusercontent.com/48112516/206332476-54c501ae-4d23-402b-9a1c-4bfd1f26956a.png)
![image](https://user-images.githubusercontent.com/48112516/206332515-0201dbca-dc07-46cf-9bde-ca444da9b337.png)

If i use nuxt3-rc.12,, it's ok, but i update this in rc.14, i got this error

**Comment by harlan-zw** [comment]
You need to upgrade to exactly version 3.0.0. Not an RC version
